server:
  port: 8081
#  servlet:
#    context-path: /practice-spring-boot

spring:
  application:
    name:practice-springboot
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/practice_spring_boot_db?createDatabaseIfNotExist=true}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  messages:
    basename:
      ValidationMessages
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
